src/SistemaCentralMonitoramento/CentralMonitoringSystem/CMS.System/Models/ErrorViewModel.cs
namespace CMS.System.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/SistemaCentralMonitoramento/CentralMonitoringSystem/CMS.System/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace CMS.System.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Registro()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Logout()
        {
            return View();
        }
    }
}

src/SistemaCentralMonitoramento/CentralMonitoringSystem/CMS.System/Controllers/DispositivosController.cs
using CMS.System.Data.Models;
using CMS.System.Data.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CMS.System.Controllers
{
    public class DispositivosController : Controller
    {
        private readonly IDispositivoRepository catalogo;
        public DispositivosController(IDispositivoRepository context)
        {
            this.catalogo = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var dispositivos = await catalogo.GetDispositivosById();

            return View(dispositivos);
        }

        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute]string id)
        {
            var dispositivo = await catalogo.GetDispositivosById(id);

            return View(dispositivo.FirstOrDefault());
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Dispositivo dispositivo)
        {
            await catalogo.UpdateDispositivo(await ValidaEdicao(dispositivo));

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete([FromRoute] string id)
        {
            var dispositivo = await catalogo.GetDispositivosById(id);

            return View(dispositivo.FirstOrDefault());
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Dispositivo dispositivo)
        {
            await catalogo.RemoveDispositivo(dispositivo.ID_DEVICE);

            return RedirectToAction("Index");
        }
        private async Task<Dispositivo> ValidaEdicao(Dispositivo dispositivo)
        {
            dispositivo.DT_ALTERACAO = DateTime.Now;

            return dispositivo;
        }
    }
}

src/SistemaCentralMonitoramento/CentralMonitoringSystem/CMS.System/Controllers/HomeController.cs
using CMS.System.Data.Models;
using CMS.System.Data.Repositories;
using CMS.System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace CMS.System.Controllers
{
    public class HomeController : Controller
    {
        private readonly IDispositivoRepository catalogo;

        public HomeController(IDispositivoRepository context)
        {
            this.catalogo = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var data = await FiltraLista(2,0,0);
            var retorno = new MedicaoViewModel(data);
            var dispositivos = await catalogo.GetDispositivosById();

            retorno.Dispositivos = dispositivos
                                        .Select(d => Convert.ToInt32(d.ID_DEVICE))
                                        .ToList();

            retorno.DispositivosGrupos = dispositivos
                                            .Where(d => d.ID_GROUP != 0)
                                            .Select(d => d.ID_GROUP)
                                            .Distinct()
                                            .ToList();
            return View(retorno);
        }
        [HttpPost]
        public async Task<IActionResult> Index(MedicaoViewModel model)
        {
            var data = await FiltraLista(model.filtro, model.DispositivoSelecionado, model.GrupoSelecionado) ;
            var retorno = new MedicaoViewModel(data, model);
            var dispositivos = await catalogo.GetDispositivosById();

            retorno.Dispositivos = dispositivos
                                        .Select(d => Convert.ToInt32(d.ID_DEVICE))
                                        .ToList();
            retorno.DispositivosGrupos = dispositivos
                                            .Where(d =>  d.ID_GROUP != 0)
                                            .Select(d => d.ID_GROUP)
                                            .Distinct()
                                            .ToList();
            return View(retorno);
        }

        private async Task<List<DispositivoMedicao>> FiltraLista(int filtro, int ID_DEVICE, int GRUPO)
         {

            var data = GRUPO != 0 ? await catalogo.GetMedicoesByGroup(GRUPO) : await catalogo.GetMedicoes();


            if (filtro == 2)
            {
                data = data.Where(c => c.DT_PUBLICACAO.Date == DateTime.Today.Date).ToList();
            }
            if (filtro == 1)
            {
                data = data.Where(c => c.DT_PUBLICACAO.Month == DateTime.Now.Month && c.DT_PUBLICACAO.Year == DateTime.Now.Year).ToList();
            }
            if (filtro == 3)
            {
                data = data.Where(c => c.DT_PUBLICACAO.Year == DateTime.Now.Year).ToList();
            }

            if(ID_DEVICE != 0)
            {
                data = data.Where( c=> c.ID_DEVICE == ID_DEVICE.ToString()).ToList();
            }
            return data;
        }
    }
}

src/SistemaCentralMonitoramento/CentralMonitoringSystem/CMS.System/Views/Dispositivos/Delete.cshtml
@model CMS.System.Data.Models.Dispositivo

@{
    ViewData["Title"] = "Delete";
}

<br/>
<br />
<br />
<h3 class="text-center">Deletar cadastro do dispositivo @Model.ID_DEVICE ?</h3>
<div>
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="ID_DEVICE" />
        <div class="text-center">
            <button type="submit" class="btn btn-danger">Excluir</button>
            <a asp-controller="Dispositivos" asp-action="Index" class="btn btn-secondary">Voltar</a>
        </div>

    </form>
</div>

src/SistemaCentralMonitoramento/CentralMonitoringSystem/CMS.System/Views/Dispositivos/Edit.cshtml
@model CMS.System.Data.Models.Dispositivo


<h4 class ="text-center"> Dispositivo @Model.ID_DEVICE</h4>
<br />
<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="ID_DEVICE" />
    <input type="hidden" asp-for="DT_CADASTRO" />
    <input type="hidden" asp-for="DT_ALTERACAO" />
    <input type="hidden" asp-for="COD_USUARIO_ALTERACAO" />
    <input type="hidden" asp-for="IND_ATIVO" />

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Grupo Controle</th>
                <th>Frequência de Atualização</th>
                <th>Umidade Ambiente</th>
                <th>Temperatura Ambiente</th>
                <th>Umidade do Solo</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input asp-for="ID_GROUP" class="form-control" />
                </td>
                <td>
                    <input asp-for="FREQUENCY" class="form-control" />
                </td>
                <td>
                    <select asp-for="IND_ATIVO_HMD_AMB" class="form-control">
                        <option value="1">Ligado</option>
                        <option value="0">Desligado</option>
                    </select>
                </td>
                <td>
                    <select asp-for="IND_ATIVO_TMP_AMB" class="form-control">
                        <option value="1">Ligado</option>
                        <option value="0">Desligado</option>
                    </select>
                </td>
                <td>
                    <select asp-for="IND_ATIVO_HMD_SOL" class="form-control">
                        <option value="1">Ligado</option>
                        <option value="0">Desligado</option>
                    </select>
                </td>
            </tr>
        </tbody>
    </table>

    <button type="submit" class="btn btn-primary">Salvar</button>
    <a asp-controller="Dispositivos" asp-action="Index" class="btn btn-secondary">Voltar</a>
</form>

src/SistemaCentralMonitoramento/CentralMonitoringSystem/CMS.System/Views/Dispositivos/Index.cshtml
@using CMS.System.Extensions;
@model IEnumerable<CMS.System.Data.Models.Dispositivo>


<section class="section dashboard d-flex align-items-center justify-content-center">
    
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Identificador</th>
                    <th scope="col">Grupo Controle</th>
                    <th scope="col">Frequência de Atualização</th>
                    <th scope="col">Umidade Ambiente</th>
                    <th scope="col">Temperatura Ambiente</th>
                    <th scope="col">Umidade do Solo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ID_DEVICE</td>
                        <td>@item.ID_GROUP</td>
                        <td>@item.FREQUENCY</td>
                        <td>@this.FormataSituacao(item.IND_ATIVO_HMD_AMB)</td>
                        <td>@this.FormataSituacao(item.IND_ATIVO_TMP_AMB)</td>
                        <td>@this.FormataSituacao(item.IND_ATIVO_HMD_SOL)</td>
                        <td>
                            <a asp-controller="Dispositivos" asp-action="Edit" asp-route-id="@item.ID_DEVICE" style="text-decoration: none;" title="Editar Cadastro">
                                <img src="~/imagens/gerais/editar.png" width="16" height="16">
                            </a>
                            <a asp-action="Delete" asp-route-id="@item.ID_DEVICE" style="text-decoration: none;" title="Deletar Cadastro">
                                <img src="~/imagens/gerais/deletar.png" width="16" height="16">
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

src/SistemaCentralMonitoramento/CentralMonitoringSystem/CMS.System/Views/Home/Index.cshtml
@using System.Globalization;
@model CMS.System.Data.Models.MedicaoViewModel

<div class="pagetitle">
    <h1>Painel Principal</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item active">Análise de Dados</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<form data-val="true" method="post" asp-controller="Home" asp-action="Index">
    <section class="section dashboard">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">

                    <div class="col-lg-4">
                        <div class="card info-card sales-card">
                            <div class="card-body">
                                <h5 class="card-title text-center">Referência</h5>
                                <div>
                                    @Html.DropDownListFor(model => model.filtro, new List<SelectListItem>
                                    {
                                        new SelectListItem {Text = "Hoje", Value = "2" , Selected = true},
                                        new SelectListItem {Text = "Este Mês", Value = "1" },
                                        new SelectListItem {Text = "Este Ano", Value = "0"  }
                                    },
                                    new {
                                        @class = "form-control",
                                        @onchange="this.form.submit()"
                                    })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="card info-card sales-card">
                            <div class="card-body">
                                <h5 class="card-title text-center">Dispositivo</h5>
                                <div>
                                    @Html.DropDownListFor(model => model.DispositivoSelecionado, new SelectList(Model.Dispositivos),
                                    "Todos",
                                    new {
                                        @class = "form-control" ,
                                        @onchange="this.form.submit()"
                                    })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="card info-card sales-card">
                            <div class="card-body">
                                <h5 class="card-title text-center">Grupo</h5>
                                <div>
                                    @Html.DropDownListFor(model => model.GrupoSelecionado, new SelectList(Model.DispositivosGrupos),
                                    "0",
                                    new {
                                    @class = "form-control" ,
                                    @onchange="this.form.submit()"
                                    })
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <br/>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div id="medicoesChart"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>





<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script>
    ////////////////////////////////////////////// Início Gráfico //////////////////////////////////////////////
    document.addEventListener("DOMContentLoaded", function () {
        var data = {
            series: 
            [
                {
                    name: 'Umidade do Ambiente',
                    data: [@foreach (var medicao in Model.Medicoes) { @string.Concat(string.Format("{0:F1}", medicao.VAL_HMD_AMB).Replace(",", "."), ",")}]
                }, 
                {
                    name: 'Temperatura do Ambiente',
                    data: [@foreach (var medicao in Model.Medicoes) { @string.Concat(string.Format("{0:F1}", medicao.VAL_TMP_AMB).Replace(",", "."), ",")}]
                }, 
                {
                    name: 'Umidade do Solo',
                    data: [@foreach (var medicao in Model.Medicoes) { @string.Concat(string.Format("{0:F1}", medicao.VAL_HMD_SOL).Replace(",", "."), ",")}]
                }
            ],
            
            chart: {
                type: 'area',
                toolbar: {
                    show: true
                },
                height: 400
            },
            colors: ['#4154f1', '#2eca6a', '#ff771d'],
            plotOptions: {
                bar: {
                    horizontal: false,
                    borderRadius: 10,
                    columnWidth: '55%',
                    endingShape: 'rounded'
                },
            },
            dataLabels: {
                enabled: false
            },
            stroke: {
                show: true,
                width: 1,
                colors: ['transparent']
            },
            grid: {
                row: {
                    colors: ['#fff', '#f2f2f2']
                }
            },
            xaxis: {
                tickPlacement: 'on',
                categories: [@foreach (var cat in Model.categoria) { @string.Concat(cat.Replace(".",""),",") }],
            },
            yaxis: {
                title: {
                    text: ' Porcentagem % '
                },
                min: 0, // Define o valor mínimo do eixo Y
                max: 100, // Define o valor máximo do eixo Y
     
            },
            fill: {
                opacity: 1
            }
        };
            
        console.log(data)

        // Renderiza o gráfico usando ApexCharts
        var chart = new ApexCharts(document.querySelector("#medicoesChart"), data);
        chart.render();
    });
    ////////////////////////////////////////////// Fim Gráfico //////////////////////////////////////////////

</script>

src/SistemaCentralMonitoramento/CentralMonitoringSystem/CMS.System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sistema Central de Monitoramento</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CMS.System.styles.css" asp-append-version="true" />

    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" id="sidebarToggle">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/imagens/layout/main_icon_monitoring.png">
                </a>
                <div class="container text-center" style="font-family: 'Audiowide', sans-serif; font-size: 40px;">
                    SISTEMA CENTRAL DE MONITORAMENTO
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row">
            <!-- Menu Lateral -->
            <nav id="sidebar" class="col-md-2 d-md-block sidebar" >
                <div class="position-sticky" style="top: 0;">
                    <ul class="nav flex-column">
                        <!-- Dashboard -->
                        <li class="nav-item">
                            <a class="nav-link collapsed" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/imagens/layout/icon_grid.png" style="width:20px;height:20px">
                                <span>Dashboard</span>
                            </a>
                        </li>
                        <!-- Dispositivos -->
                        <li class="nav-item">
                            <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                                <img src="~/imagens/layout/icon_sensor.png" style="width:20px;height:20px">
                                <i class="bi bi-menu-button-wide"></i><span>Dispositivos</span><i class="bi bi-chevron-down ms-auto"></i>
                            </a>
                            <ul id="components-nav" class="collapse">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Dispositivos" asp-action="Index">
                                        <img src="~/imagens/layout/icon_cadastro.png" style="width:20px;height:20px">
                                        <span>Cadastro</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!-- Perfil -->
                        <li class="nav-item">
                            <a class="nav-link collapsed" data-bs-target="#components-nav2" data-bs-toggle="collapse" href="#">
                                <img src="~/imagens/layout/icon_profile.png" style="width:20px;height:20px">
                                <span>Perfil</span>
                            </a>
                            <ul id="components-nav2" class="collapse ">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">
                                        <img src="~/imagens/layout/icon_login.png" style="width:20px;height:20px">
                                        <span>Login</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">
                                        <img src="~/imagens/layout/icon_logout.png" style="width:20px;height:20px">
                                        <span>Logout</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!-- Registro -->
                        <li class="nav-item">
                            <a class="nav-link collapsed" asp-area="" asp-controller="Account" asp-action="Registro">
                                <img src="~/imagens/layout/icon_registro.png" style="width:20px;height:20px">
                                <span>Registro</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>


            <!-- Conteúdo Principal -->
            <main class="col-md-10">
                <div style="min-height: 690px;">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>

    <footer class="section-footer border-top" style="padding-top:30px">
        <div class="container mx-auto">
            <section class="footer-top padding-y" style="text-align:center">
                <div class="row ">
                    <aside class="col-md-4">
                        <article class="mr-3">
                            
                        </article>
                    </aside>
                    <aside class="col-sm-4 col-md-3 ">
                        
                        <p class="float-right text-muted" style="font-family: 'Audiowide', sans-serif;">
                            Sistema desenvolvido para o TCC do curso de Engenharia da Computação.
                        </p>
                    </aside>

                </div>
            </section>

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>




</html>